// Code generated by ent, DO NOT EDIT.

package ent

import (
	"beer-shop/app/catalog/internal/data/ent/beer"
	"beer-shop/app/catalog/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	beerFields := schema.Beer{}.Fields()
	_ = beerFields
	// beerDescCreatedAt is the schema descriptor for created_at field.
	beerDescCreatedAt := beerFields[6].Descriptor()
	// beer.DefaultCreatedAt holds the default value on creation for the created_at field.
	beer.DefaultCreatedAt = beerDescCreatedAt.Default.(func() time.Time)
	// beerDescUpdatedAt is the schema descriptor for updated_at field.
	beerDescUpdatedAt := beerFields[7].Descriptor()
	// beer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	beer.DefaultUpdatedAt = beerDescUpdatedAt.Default.(func() time.Time)
}
